name: Build

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
      - develop
      - feature_*

jobs:
  build:
    runs-on: ubuntu-latest
    container: zephyrprojectrtos/ci:v0.26.4
    env:
      CMAKE_PREFIX_PATH: /opt/toolchains
      build_option: "-- -DSHIELD=xen_dom0"
    strategy:
      matrix:
        platform: [native_posix_64]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Initialize
        run: |
          sudo apt update
          sudo apt install libprotobuf-dev -y
          west init -l ./
          west update
          west zephyr-export
          echo "BUILD_OPTION=${{ env.build_option }}" >> $GITHUB_ENV

      - name: Set option
        if: startsWith(matrix.platform, 'native_posix_64')
        run: |
         echo "opt = $BUILD_OPTION"
         echo "export BUILD_OPTION= "
         echo "opt after = $BUILD_OPTION"

      - name: Build ${{ matrix.platform }}
        run: |
          echo "opt before build = $BUILD_OPTION"
  

      - name: Tests
        if: startsWith(matrix.platform, 'native_posix_64')
        run: |
          
          gcovr twister-out/native_posix_64/ -f src/ --xml-pretty > ./coverage.xml

      - name: Upload codecov report
        if: startsWith(matrix.platform, 'native_posix_64')
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./coverage.xml
